from config.Items import Items, items_by_id, INITIAL_INVENTORY, INITIAL_INVENTORY_AFTER_TUTORIAL
from config.NPCs import NPCs, NPC, INITIALY_LOCKED_NPCS, TUTORIAL_UNLOCK
from config.Scores import INVENTORY_SCORES, UNLOCK_SCORES, DUEL_SCORE
