from config.Items import Items
from config.NPCs import NPCs

INVENTORY_SCORES = {
    Items.TeleFart.id: 42,
    Items.TonyStank.id: 136,
    Items.Grooviton.id: 126,
    Items.Flashfunk.id: 64,
    Items.HonkHonk.id: 5,
    Items.GongLong.id: 16,
    Items.PlantPlug.id: 197,
    Items.SugarCrush.id: 5,
    Items.NastyNoodles.id: 17,
    Items.PocketHole.id: 1000,
    Items.MirrorMirror.id: 870,
    Items.SnoozeBest.id: 11,
    Items.ForkThis.id: 6,
    Items.ClementEye.id: 14,
    Items.DeFeeters.id: 87,
    Items.Hypnomon.id: 172,
    Items.ShimmerGlimmer.id: 6,
    Items.DurianGrey.id: 94,
    Items.OminousOnion.id: 8,
    Items.Skelebowl.id: 38,
    Items.HolyMoly.id: 1337,
    Items.CalciumFancium.id: 15,
    Items.StingySullivan.id: 49,
    Items.BlingRing.id: 186,
    Items.CactusJack.id: 0,
    Items.DiamondDough.id: 71,
    Items.SlitheringSoup.id: 150,
    Items.Smellmonell.id: 50,
    Items.NosyNolan.id: 47,
    Items.CloakKent.id: 31,
    Items.FoxyBoxy.id: 34,
    Items.FattyPatty.id: 0,
    Items.RainbowMunch.id: 113,
    Items.WonderWall.id: 0,
}

UNLOCK_SCORES = {
    NPCs['D1'].id: 150,
    NPCs['M4'].id: 100,
    NPCs['D6'].id: 50,
    NPCs['T8'].id: 300,
    NPCs['D11'].id: 350,
    NPCs['D2'].id: 200,
}

DUEL_SCORE = {
    NPCs['D1'].id: 75,
    NPCs['D2'].id: 75,
    NPCs['D3'].id: 150,
    NPCs['D4'].id: 25,
    NPCs['D5'].id: 25,
    NPCs['D6'].id: 125,
    NPCs['D7'].id: 150,
    NPCs['D8'].id: 75,
    NPCs['D9'].id: 25,
    NPCs['D10'].id: 100,
    NPCs['D11'].id: 75,
    NPCs['D12'].id: 50,
    NPCs['D13'].id: 10000,
    NPCs['D14'].id: 100,
    NPCs['D15'].id: 150,
    NPCs['TD1'].id: 5,
}